(() => {
  let rows = [];
  const $ = (id) => document.getElementById(id);
  const money = (v) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(v || 0));
  const dateTime = (iso) => iso ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(iso)) : '—';
  const clean = (v) => String(v || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const statusLabel = { approved:'Aprovado', pending:'Aguardando', rejected:'Recusado', cancelled:'Cancelado', refunded:'Estornado', review:'Revisar', checkout_error:'Erro checkout' };
  const paymentLabel = { pix:'PIX', card:'Cartão' };
  function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function showLogin(){$('loginSection').classList.remove('hidden');$('dashboardSection').classList.add('hidden')}
  function showDashboard(){$('loginSection').classList.add('hidden');$('dashboardSection').classList.remove('hidden')}
  function hydrateTrips(){const trips=[...new Map(rows.filter(r=>r.tripId).map(r=>[r.tripId,r.tripTitle])).entries()];$('tripFilter').innerHTML='<option value="">Todos os passeios</option>'+trips.map(([id,title])=>`<option value="${escapeHtml(id)}">${escapeHtml(title)}</option>`).join('')}
  function render(){const q=clean($('searchAdmin').value),status=$('statusFilter').value,trip=$('tripFilter').value;const filtered=rows.filter(r=>{const haystack=clean([r.id,r.tripTitle,r.variantName,r.customer?.name,r.customer?.cpf,r.customer?.phone,r.customer?.email,r.mpPaymentId].join(' '));return(!q||haystack.includes(q))&&(!status||r.status===status)&&(!trip||r.tripId===trip)});if(!filtered.length){$('reservationsBody').innerHTML='<tr><td colspan="8" class="empty">Nenhuma reserva encontrada.</td></tr>';return}$('reservationsBody').innerHTML=filtered.map(r=>`<tr><td class="name-cell"><strong>${escapeHtml(r.customer?.name||'—')}</strong><small>${escapeHtml(r.customer?.phone||'')} • ${escapeHtml(r.customer?.email||'')}</small><small>CPF: ${escapeHtml(r.customer?.cpf||'—')}</small></td><td class="name-cell"><strong>${escapeHtml(r.tripTitle)}</strong><small>${escapeHtml(r.variantName)} • Qtd. ${escapeHtml(r.quantity||1)}</small></td><td class="nowrap"><strong>${escapeHtml(r.id)}</strong></td><td class="nowrap"><strong>${money(r.amountPaid??r.amount)}</strong><div style="color:#82958a;margin-top:4px">Previsto: ${money(r.amount)}</div></td><td><strong>${escapeHtml(paymentLabel[r.paymentMethod]||r.paymentMethod||'—')}</strong><div style="color:#82958a;margin-top:4px">${r.installments>1?`${r.installments}x`:'À vista'}</div></td><td><span class="status ${escapeHtml(r.status)}">${escapeHtml(statusLabel[r.status]||r.status)}</span></td><td class="nowrap">${escapeHtml(dateTime(r.approvedAt||r.createdAt))}</td><td><div class="mpid">${escapeHtml(r.mpPaymentId||'Aguardando ID')}</div><div class="mpid">${escapeHtml(r.paymentMethodId||'')}</div></td></tr>`).join('')}
  async function loadIntegrations(){try{const response=await fetch('/api/integrations-status',{cache:'no-store'});if(!response.ok)return;const data=await response.json();const labels=[['mercadoPago','Mercado Pago'],['webhook','Webhook'],['reservations','Reservas MP'],['appUrl','URL produção'],['adminSession','Painel seguro']];$('integrationBar').innerHTML=labels.map(([key,label])=>`<div class="integration-item ${data.status?.[key]?'ok':'no'}"><span>${label}</span><strong>${data.status?.[key]?'● Conectado':'● Pendente'}</strong></div>`).join('');$('readyBanner').classList.toggle('warning',!data.readyForPayments);$('readyBanner').textContent=data.readyForPayments?'✓ Sistema pronto para receber pagamentos automáticos.':'⚠ Ainda faltam configurações antes de liberar pagamentos reais.';}catch{}}
  async function load(){$('reservationsBody').innerHTML='<tr><td colspan="8" class="empty">Atualizando dados do Mercado Pago...</td></tr>';const response=await fetch('/api/admin-reservations',{cache:'no-store'});if(response.status===401)return showLogin();const data=await response.json();if(!response.ok)throw new Error(data.error||'Erro ao carregar painel');rows=data.rows||[];$('kpiRevenue').textContent=money(data.summary?.revenue||0);$('kpiApproved').textContent=data.summary?.approved||0;$('kpiSeats').textContent=data.summary?.seats||0;$('kpiPending').textContent=data.summary?.pending||0;hydrateTrips();showDashboard();render();await loadIntegrations()}
  $('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMessage').textContent='';const response=await fetch('/api/admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('adminPassword').value})});const data=await response.json();if(!response.ok)return $('loginMessage').textContent=data.error||'Não foi possível entrar.';$('adminPassword').value='';await load()});
  $('logoutBtn').addEventListener('click',async()=>{await fetch('/api/admin-logout',{method:'POST'});rows=[];showLogin()});$('refreshBtn').addEventListener('click',()=>load().catch(e=>alert(e.message)));$('searchAdmin').addEventListener('input',render);$('statusFilter').addEventListener('change',render);$('tripFilter').addEventListener('change',render);$('clearFilters').addEventListener('click',()=>{$('searchAdmin').value='';$('statusFilter').value='';$('tripFilter').value='';render()});
  $('exportBtn').addEventListener('click',()=>{const header=['Reserva','Nome','CPF','WhatsApp','Email','Passeio','Opção','Quantidade','Valor','Forma','Status','Pagamento Mercado Pago','Data'];const csvRows=rows.map(r=>[r.id,r.customer?.name,r.customer?.cpf,r.customer?.phone,r.customer?.email,r.tripTitle,r.variantName,r.quantity,r.amountPaid??r.amount,paymentLabel[r.paymentMethod]||r.paymentMethod,statusLabel[r.status]||r.status,r.mpPaymentId||'',r.approvedAt||r.createdAt]);const csv=[header,...csvRows].map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`reservas-trilheiros-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)});
  load().catch(()=>showLogin());
})();